export const CATEGORIE_CONVENZIONI_NAZIONALI = [
  "Abbigliamento",
  "Alimentari",
  "Arredamento",
  "Autoricambi",
  "Centri medici",
  "Impianti Termici",
  "Palestre",
  "Parchi Giochi",
  "Ristrutturazioni",
  "Studi Legali Centro",
  "Studi Legali Nord",
  "Studi Legali Sicilia",
  "Studi Legali Sud",
  "Energia",
  "Gommisti",
  "Odontoiatri",
  "Assicurazioni e Servizi Finanziari",
  "Officina",
  "Psicologi",
  "Auto",
  "Benessere e cura della persona",
  "Campus",
  "Casa",
  "Cultura",
  "Moto, scooter e bici",
  "Medicina legale",
  "Salute",
  "Corporate Benefits",
  "Patronati e CAF",
  "Sport",
  "Trasporti",
  "Turismo",
];

export const CATEGORIE_CASHBACK_FORZE_ARMATE = [
  "Vacanze e Viaggi",
  "Tempo Libero",
  "Tecnologia e Elettrodomestici",
  "Alimentari e Supermercati",
  "Gift Card",
  "Moda",
  "Articoli sportivi",
  "Profumeria e Cosmetica",
  "Salute e Cura della persona",
  "Cura della Casa",
  "Famiglia",
  "Cashback365",
];
