export const CATEGORIE_CONVENZIONI_NAZIONALI = [
  "Abbigliamento",
  "Alimentari",
  "Arredamento",
  "Autoricambi",
  "Centri medici",
  "Impianti Termici",
  "Palestre",
  "Parchi Giochi",
  "Ristrutturazioni",
  "Studi Legali Centro",
  "Studi Legali Nord",
  "Studi Legali Sicilia",
  "Studi Legali Sud",
  "Energia",
  "Gommisti",
  "Odontoiatri",
  "Assicurazioni e Servizi Finanziari",
  "Officina",
  "Psicologi",
  "Auto",
  "Benessere e cura della persona",
  "Campus",
  "Casa",
  "Cultura",
  "Moto, scooter e bici",
  "Medicina legale",
  "Salute",
  "Corporate Benefits",
  "Patronati e CAF",
  "Sport",
  "Trasporti",
  "Turismo",
];
